### ISSUE TITLE
check_params should check if the argnames are the same

### ISSUE THREAD

**Issue by janfrancu** [aicenter/GenerativeAD.jl#30]
Check parames throws key errors, when the key/parameter names have changed.
Fix by comparing the keys first before, `get` is called in the following code.
```
for params in saved_params
        all(map(k->params[String(k)] == parameters[k], collect(keys(parameters)))) ? (return false) : nothing
    end
```

**Comment by vitskvara** [comment]
https://github.com/aicenter/GenerativeAD.jl/pull/35
